/**
 * gbrain-adapter.ts
 * Wraps the `gbrain` CLI via Node.js child_process for async operations.
 *
 * All five operations (putPage / getPage / listPages / deletePage /
 * extractLinks) are exported as typed async functions.
 *
 * gbrain binary is expected to be on PATH (installed via `bun link` per
 * RUNBOOK.md).
 */

import { execFile } from 'child_process';
import { promisify } from 'util';

const execFileAsync = promisify(execFile);

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Structured representation of a page to be stored in gbrain. */
export interface GbrainPage {
  /** Used as the gbrain slug. Notion page_id works directly. */
  id: string;
  title: string;
  /** Body markdown (frontmatter is generated by putPage from id/title/metadata). */
  content: string;
  /** Extra fields to embed in YAML frontmatter (e.g. { source: 'projects' }). */
  metadata?: Record<string, unknown>;
}

/** Result returned by `gbrain put` (write-summary, not full page). */
export interface PutPageResult {
  slug: string;
  status: string;
  chunks: number;
  auto_links?: Record<string, unknown>;
  auto_timeline?: Record<string, unknown>;
}

/** Minimal descriptor returned by listPages. */
export interface GbrainPageSummary {
  id: string;
  title: string;
}

/** Options accepted by extractLinks. */
export interface ExtractLinksOptions {
  /** Maximum number of links to return (default: unbounded). */
  limit?: number;
}

// ---------------------------------------------------------------------------
// Internal helper
// ---------------------------------------------------------------------------

/**
 * Run a `gbrain` sub-command and return parsed JSON output.
 * Throws on non-zero exit code.
 */
async function runGbrain<T>(args: string[]): Promise<T> {
  const { stdout } = await execFileAsync('gbrain', args, {
    env: process.env,
  });
  const trimmed = stdout.trim();
  if (!trimmed) {
    return undefined as unknown as T;
  }
  return JSON.parse(trimmed) as T;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Build a YAML frontmatter block from a page's id, title, and metadata.
 * Used internally by putPage to produce gbrain-compatible content.
 */
function buildFrontmatter(page: GbrainPage): string {
  const lines = [
    '---',
    `notion_page_id: ${page.id}`,
    `title: ${JSON.stringify(page.title)}`,
  ];
  for (const [k, v] of Object.entries(page.metadata ?? {})) {
    lines.push(`${k}: ${JSON.stringify(v)}`);
  }
  lines.push('---', '');
  return lines.join('\n');
}

/**
 * Write (or overwrite) a page in the gbrain knowledge graph.
 * Uses Notion page_id as the gbrain slug; YAML frontmatter is composed from
 * title and metadata.
 *
 * @param page - Page payload. `id` becomes the slug, `content` is body markdown.
 * @returns Write-summary from gbrain (slug, status, chunk count, auto-links).
 */
export async function putPage(page: GbrainPage): Promise<PutPageResult> {
  const fullContent = buildFrontmatter(page) + page.content;
  return runGbrain<PutPageResult>([
    'put',
    page.id,
    '--content', fullContent,
  ]);
}

/**
 * Retrieve a single page from the gbrain knowledge graph by slug.
 *
 * TODO Phase 2: gbrain CLI `get <slug>` prints markdown, not JSON — runGbrain's
 * JSON.parse will throw. Switch this to use raw stdout when implementing pull-back.
 *
 * @param id - The page slug (Notion page_id).
 */
export async function getPage(id: string): Promise<GbrainPage> {
  return runGbrain<GbrainPage>(['get', id]);
}

/**
 * List all pages currently stored in the gbrain knowledge graph.
 *
 * TODO Phase 2: gbrain CLI `list` defaults to human-readable output;
 * may need `--json` flag (untested) or output parsing.
 */
export async function listPages(): Promise<GbrainPageSummary[]> {
  const result = await runGbrain<GbrainPageSummary[] | null>(['list']);
  return result ?? [];
}

/**
 * Delete a page from the gbrain knowledge graph.
 *
 * @param id - The page slug (Notion page_id) to remove.
 */
export async function deletePage(id: string): Promise<void> {
  await runGbrain<void>(['delete', id]);
}

/**
 * Extract outbound links from a page in the gbrain graph.
 *
 * Note: `--source` and `--since` flags mentioned in plan.md have NOT been
 * verified against the gbrain CLI.
 * TODO: verify --source / --since flag exists in gbrain CLI before enabling.
 *
 * @param pageId - The source page ID to extract links from.
 * @param options - Optional extraction configuration.
 * @returns Array of linked page IDs.
 */
export async function extractLinks(
  pageId: string,
  options: ExtractLinksOptions = {},
): Promise<string[]> {
  const args = ['extract', 'links', '--page-id', pageId, '--json'];
  if (options.limit !== undefined) {
    args.push('--limit', String(options.limit));
  }
  const result = await runGbrain<string[] | null>(args);
  return result ?? [];
}
